# 后端服务监听地址
app_host = "0.0.0.0"
# 后端服务端口
app_port = 8000
# 代理监听地址
proxy_host = "127.0.0.1"
# 代理监听端口
proxy_port = 8081
# 数据库类型: sqlite 或 mysql
db_type = "mysql"

[mysql]
# MySQL 主机地址
host = "127.0.0.1"
# MySQL 端口
port = 3306
# MySQL 用户名
user = "root"
# MySQL 密码
password = "root"
# MySQL 数据库名
database = "proxy_insight"
